require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BlueprintUsersController do

  # This should return the minimal set of attributes required to create a valid
  # BlueprintUser. As you add validations to BlueprintUser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "blueprint_id" => "1", "user_id" => "1", "preferred_decryptor" => "1"} }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BlueprintUsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all blueprint_users as @blueprint_users" do
      blueprint_user = BlueprintUser.create! valid_attributes
      get :index, {}, valid_session
      assigns(:blueprint_users).should eq([blueprint_user])
    end
  end

  describe "GET show" do
    it "assigns the requested blueprint_user as @blueprint_user" do
      blueprint_user = BlueprintUser.create! valid_attributes
      get :show, {:id => blueprint_user.to_param}, valid_session
      assigns(:blueprint_user).should eq(blueprint_user)
    end
  end

  describe "GET new" do
    it "assigns a new blueprint_user as @blueprint_user" do
      get :new, {}, valid_session
      assigns(:blueprint_user).should be_a_new(BlueprintUser)
    end
  end

  describe "GET edit" do
    it "assigns the requested blueprint_user as @blueprint_user" do
      blueprint_user = BlueprintUser.create! valid_attributes
      get :edit, {:id => blueprint_user.to_param}, valid_session
      assigns(:blueprint_user).should eq(blueprint_user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BlueprintUser" do
        expect {
          post :create, {:blueprint_user => valid_attributes}, valid_session
        }.to change(BlueprintUser, :count).by(1)
      end

      it "assigns a newly created blueprint_user as @blueprint_user" do
        post :create, {:blueprint_user => valid_attributes}, valid_session
        assigns(:blueprint_user).should be_a(BlueprintUser)
        assigns(:blueprint_user).should be_persisted
      end

      it "redirects to the created blueprint_user" do
        post :create, {:blueprint_user => valid_attributes}, valid_session
        response.should redirect_to(BlueprintUser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved blueprint_user as @blueprint_user" do
        # Trigger the behavior that occurs when invalid params are submitted
        BlueprintUser.any_instance.stub(:save).and_return(false)
        post :create, {:blueprint_user => { "blueprint_id" => "invalid value" }}, valid_session
        assigns(:blueprint_user).should be_a_new(BlueprintUser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BlueprintUser.any_instance.stub(:save).and_return(false)
        post :create, {:blueprint_user => { "blueprint_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested blueprint_user" do
        blueprint_user = BlueprintUser.create! valid_attributes
        # Assuming there are no other blueprint_users in the database, this
        # specifies that the BlueprintUser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BlueprintUser.any_instance.should_receive(:update).with({ "blueprint_id" => "1" })
        put :update, {:id => blueprint_user.to_param, :blueprint_user => { "blueprint_id" => "1" }}, valid_session
      end

      it "assigns the requested blueprint_user as @blueprint_user" do
        blueprint_user = BlueprintUser.create! valid_attributes
        put :update, {:id => blueprint_user.to_param, :blueprint_user => valid_attributes}, valid_session
        assigns(:blueprint_user).should eq(blueprint_user)
      end

      it "redirects to the blueprint_user" do
        blueprint_user = BlueprintUser.create! valid_attributes
        put :update, {:id => blueprint_user.to_param, :blueprint_user => valid_attributes}, valid_session
        response.should redirect_to(blueprint_user)
      end
    end

    describe "with invalid params" do
      it "assigns the blueprint_user as @blueprint_user" do
        blueprint_user = BlueprintUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BlueprintUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => blueprint_user.to_param, :blueprint_user => { "blueprint_id" => "invalid value" }}, valid_session
        assigns(:blueprint_user).should eq(blueprint_user)
      end

      it "re-renders the 'edit' template" do
        blueprint_user = BlueprintUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BlueprintUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => blueprint_user.to_param, :blueprint_user => { "blueprint_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested blueprint_user" do
      blueprint_user = BlueprintUser.create! valid_attributes
      expect {
        delete :destroy, {:id => blueprint_user.to_param}, valid_session
      }.to change(BlueprintUser, :count).by(-1)
    end

    it "redirects to the blueprint_users list" do
      blueprint_user = BlueprintUser.create! valid_attributes
      delete :destroy, {:id => blueprint_user.to_param}, valid_session
      response.should redirect_to(blueprint_users_url)
    end
  end

end
