require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BlueprintsController do

  # This should return the minimal set of attributes required to create a valid
  # Blueprint. As you add validations to Blueprint, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BlueprintsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all blueprints as @blueprints" do
      blueprint = Blueprint.create! valid_attributes
      get :index, {}, valid_session
      assigns(:blueprints).should eq([blueprint])
    end
  end

  describe "GET show" do
    it "assigns the requested blueprint as @blueprint" do
      blueprint = Blueprint.create! valid_attributes
      get :show, {:id => blueprint.to_param}, valid_session
      assigns(:blueprint).should eq(blueprint)
    end
  end

  describe "GET new" do
    it "assigns a new blueprint as @blueprint" do
      get :new, {}, valid_session
      assigns(:blueprint).should be_a_new(Blueprint)
    end
  end

  describe "GET edit" do
    it "assigns the requested blueprint as @blueprint" do
      blueprint = Blueprint.create! valid_attributes
      get :edit, {:id => blueprint.to_param}, valid_session
      assigns(:blueprint).should eq(blueprint)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Blueprint" do
        expect {
          post :create, {:blueprint => valid_attributes}, valid_session
        }.to change(Blueprint, :count).by(1)
      end

      it "assigns a newly created blueprint as @blueprint" do
        post :create, {:blueprint => valid_attributes}, valid_session
        assigns(:blueprint).should be_a(Blueprint)
        assigns(:blueprint).should be_persisted
      end

      it "redirects to the created blueprint" do
        post :create, {:blueprint => valid_attributes}, valid_session
        response.should redirect_to(Blueprint.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved blueprint as @blueprint" do
        # Trigger the behavior that occurs when invalid params are submitted
        Blueprint.any_instance.stub(:save).and_return(false)
        post :create, {:blueprint => { "name" => "invalid value" }}, valid_session
        assigns(:blueprint).should be_a_new(Blueprint)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Blueprint.any_instance.stub(:save).and_return(false)
        post :create, {:blueprint => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested blueprint" do
        blueprint = Blueprint.create! valid_attributes
        # Assuming there are no other blueprints in the database, this
        # specifies that the Blueprint created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Blueprint.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => blueprint.to_param, :blueprint => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested blueprint as @blueprint" do
        blueprint = Blueprint.create! valid_attributes
        put :update, {:id => blueprint.to_param, :blueprint => valid_attributes}, valid_session
        assigns(:blueprint).should eq(blueprint)
      end

      it "redirects to the blueprint" do
        blueprint = Blueprint.create! valid_attributes
        put :update, {:id => blueprint.to_param, :blueprint => valid_attributes}, valid_session
        response.should redirect_to(blueprint)
      end
    end

    describe "with invalid params" do
      it "assigns the blueprint as @blueprint" do
        blueprint = Blueprint.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Blueprint.any_instance.stub(:save).and_return(false)
        put :update, {:id => blueprint.to_param, :blueprint => { "name" => "invalid value" }}, valid_session
        assigns(:blueprint).should eq(blueprint)
      end

      it "re-renders the 'edit' template" do
        blueprint = Blueprint.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Blueprint.any_instance.stub(:save).and_return(false)
        put :update, {:id => blueprint.to_param, :blueprint => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested blueprint" do
      blueprint = Blueprint.create! valid_attributes
      expect {
        delete :destroy, {:id => blueprint.to_param}, valid_session
      }.to change(Blueprint, :count).by(-1)
    end

    it "redirects to the blueprints list" do
      blueprint = Blueprint.create! valid_attributes
      delete :destroy, {:id => blueprint.to_param}, valid_session
      response.should redirect_to(blueprints_url)
    end
  end

end
